[package]
description = "Knife框架基础工具包"
edition = "2021"
license = "Apache-2.0"
name = "knife-util"
repository = "https://github.com/ocaso1987/knife-util/"
version = "0.1.0"

[dependencies]
handlebars = "4.3.3"
lazy_static = "1.4.0"
regex = "1.6.0"
serde = { version = "1.0.142", features = ["derive"] }
serde_json = "1.0.83"
futures = { version = "0.3.21", features = ["thread-pool"] }
tokio = { version = "1.20.1", features = ["full"] }
hyper = { version = "0.14.20", features = ["full"] }
serde_yaml = "0.9.4"
toml = "0.5.9"
async-trait = "0.1.57"
chrono = "0.4.20"
ctor = "0.1.23"

[features]
default = []
