[package]
description = "Knife框架基础工具包"
edition = "2021"
license = "Apache-2.0"
name = "knife-util"
repository = "https://github.com/ocaso1987/knife-util/"
version = "0.1.0"

[dependencies]
async-trait = "0.1.57"
typetag = "0.2.3"
lazy_static = "1.4.0"
# futures = { version = "0.3.21", features = ["thread-pool"] }
chrono = "0.4.21"
regex = "1.6.0"
serde = { version = "1.0.143", features = ["derive"] }
serde_json = "1.0.83"
serde_yaml = "0.9.4"
toml = "0.5.9"
ctor = "0.1.23"
handlebars = "4.3.3"
clap = "3.2.17"
tokio = { version = "1.20.1", features = ["full"] }
hyper = { version = "0.14.20", features = ["full"] }

[features]
default = []
